name: "Build and unit test"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      applicationName:
        description: 'Application name (eg: "fn-stakeholders-system-api")'
        required: true
      majorVersion:
        description: 'Major version number (eg: "v1")'
        required: true

jobs:
  build:
    name: Build and unit test the application
    runs-on: ubuntu-latest

    env:
      ## Cloudhub Properties -- Reference: https://docs.mulesoft.com/mule-runtime/4.3/deploy-to-cloudhub
      CLOUDHUB_APPLICATION_NAME: ${{ github.event.inputs.applicationName }}-${{ github.event.inputs.majorVersion }}-dev
      CLOUDHUB_ENVIRONMENT: development
      CLOUDHUB_WORKERS: 1
      CLOUDHUB_WORKER_TYPE: Micro
      CLOUDHUB_REGION: us-east-1
      CLOUDHUB_BUSINESS_GROUP_ID: 45e92f98-058f-4716-850d-bba6d068e4da
      CLOUDHUB_CONNECTED_APP_CLIENT_ID: ${{ secrets.CLOUDHUB_API_TEAM_CONNECTED_APP_CLIENT_ID_DEV }}
      CLOUDHUB_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CLOUDHUB_API_TEAM_CONNECTED_APP_CLIENT_SECRET_DEV }}
      ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.CLOUDHUB_API_TEAM_ANYPOINT_PLATFORM_CLIENT_ID_DEV }}
      ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.CLOUDHUB_API_TEAM_ANYPOINT_PLATFORM_CLIENT_SECRET_DEV }}
      ANYPOINT_PLATFORM_ANALYTICS_AGENT_ENABLED: true

      ## Mulesoft Nexus Repository Credentials
      MULE_NEXUS_USERNAME: ${{ secrets.MULE_NEXUS_USERNAME }}
      MULE_NEXUS_PASSWORD: ${{ secrets.MULE_NEXUS_PASSWORD }}

      ## App Specific Properties

      # Environment Specific
      MULE_KEY: ${{ secrets.MULE_KEY_DEV }}
      MULE_ENV: development
      MULE_RUNTIME: 4.3.0
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/settings.xml') }}
        restore-keys: ${{ runner.os }}-m2   
    - name: Retrieve Exchange access token
      run: |
        export EXCHANGE_ACCESS_TOKEN=$(curl -s "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" \
          -X POST -H "Content-Type: application/json" \
          -d "{\"grant_type\": \"client_credentials\", \"client_id\": \"$CLOUDHUB_CONNECTED_APP_CLIENT_ID\", \"client_secret\": \"$CLOUDHUB_CONNECTED_APP_CLIENT_SECRET\"}" \
          | sed -n 's|.*"access_token":"\([^"]*\)".*|\1|p')
        echo EXCHANGE_API_TEAM_ACCESSS_TOKEN=$EXCHANGE_ACCESS_TOKEN >> $GITHUB_ENV
        echo EXCHANGE_CORE_ACCESS_TOKEN=$EXCHANGE_ACCESS_TOKEN >> $GITHUB_ENV
    - name: Build and test
      run: mvn clean package 
        -s settings.xml 
        -Dmule.key="$MULE_KEY" 