name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Number of version (eg: 1.1.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionNumber }} ${{ github.ref }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number
      run: |
       mvn versions:set -DnewVersion=${{ github.event.inputs.versionNumber }}
       mvn versions:commit
    - name: Commit changes on pom.xml
      id: make-commit
      run: |
        git add pom.xml
        git commit -m "Prepare release ${{ github.event.inputs.versionNumber }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionNumber }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionNumber }}
       base: main
       title: v${{ github.event.inputs.versionNumber }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.